# Generated by Django 5.1.1 on 2024-11-08 06:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='newcategory', max_length=20)),
            ],
            options={
                'verbose_name': 'Category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Product_Name', max_length=30)),
                ('description', models.TextField(blank=True, default='My_description', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=20.0, max_digits=7)),
                ('activation_period', models.DurationField(default=datetime.timedelta(seconds=7200))),
                ('image', models.ImageField(default='Photos/24/09/17/images.png', upload_to='Photos/%y/%m/%d')),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.category')),
            ],
            options={
                'verbose_name': 'Product',
                'ordering': ['name'],
            },
        ),
    ]
