# Generated by Django 5.1.1 on 2024-11-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='download_file',
            field=models.FileField(default='Photos/24/09/17/file<built-in function id>.exe', upload_to='Downloads/%y/%m/%d'),
        ),
    ]
