# Generated by Django 5.1.1 on 2024-11-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_download_file_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='download_file_version',
            field=models.CharField(default='1.0.0', max_length=10),
        ),
    ]
