# Generated by Django 5.1.1 on 2024-12-22 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_remove_media_playlist_folder_media_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='folder',
        ),
        migrations.AddField(
            model_name='media',
            name='playlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='downloader.playlist'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
