# Generated by Django 5.1.1 on 2024-12-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0003_remove_media_folder_media_playlist_delete_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='file_name',
            new_name='title',
        ),
    ]
