# Generated by Django 5.1.1 on 2024-11-08 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_activation_period'),
        ('cart', '0004_alter_cartitem_product'),
        ('checkout', '0012_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
