# Generated by Django 5.1.1 on 2024-10-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='order',
        ),
    ]
