# Generated by Django 5.1.1 on 2024-10-30 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_remove_order_token'),
        ('generator', '0002_remove_token_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.order'),
        ),
    ]
