# Generated by Django 5.1.1 on 2024-10-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_token_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
