# Generated by Django 5.1.1 on 2024-10-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_created_at_alter_order_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='unique_code',
        ),
    ]
