# Generated by Django 5.1.1 on 2024-10-30 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_order_created_at_remove_order_expires_at_and_more'),
        ('generator', '0002_remove_token_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.token'),
        ),
    ]
