# Generated by Django 5.1.1 on 2024-10-30 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_order_token'),
        ('generator', '0002_remove_token_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.token'),
        ),
    ]
