# Generated by Django 5.1.1 on 2024-10-30 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_remove_order_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
