# Generated by Django 5.1.1 on 2024-10-31 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_orderitem_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
    ]
