# Generated by Django 5.1.1 on 2024-10-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersprofile',
            old_name='username',
            new_name='user',
        ),
    ]
