# Generated by Django 5.1.1 on 2024-10-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_username_usersprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usersprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='usersprofile',
            name='lastname',
        ),
    ]
