# Generated by Django 5.1.1 on 2024-11-02 15:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_usersprofile_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersProfile',
            new_name='UserProfile',
        ),
    ]
