# Generated by Django 5.1.1 on 2024-12-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_rename_usersprofile_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.TextField(null=True, unique=True),
        ),
    ]
