# Generated by Django 5.1.1 on 2024-12-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_userprofile_spotify_autherized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='spotify_autherized',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_spotify_autherized',
            field=models.BooleanField(default=False),
        ),
    ]
