# Generated by Django 5.1.1 on 2024-09-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('description', models.CharField(max_length=24)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('image', models.ImageField(upload_to='Photos/%y/%m/%d')),
                ('state', models.BooleanField(default=True)),
            ],
        ),
    ]
