# Generated by Django 5.1.1 on 2024-09-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catigory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catigory', models.CharField(default='newcatigory', max_length=20)),
            ],
            options={
                'verbose_name': 'Catigorie',
                'ordering': ['catigory'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='My_description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='Photos/24/09/17/images.png', upload_to='Photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Product_Name', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
    ]
